### ISSUE TITLE
Google Colab Notebook Errors

### ISSUE THREAD

**Issue by impulsecorp** [ogunlao/saint#1]
The Insurance Data Colab Notebook you link to at https://colab.research.google.com/github/ogunlao/saint/blob/main/notebooks/Insurance_Dataset.ipynb  gives an error for this part:
from saint.src.config import args
ModuleNotFoundError: No module named 'saint.src.config'

The Income Dataset Colab Notebook gives this error at 
https://colab.research.google.com/github/ogunlao/saint/blob/main/notebooks/Income_Dataset.ipynb
ERROR: Could not find a version that satisfies the requirement hydra==1.0.4 (from versions: 1.0, 1.1, 1.2, 2.1, 2.2, 2.3, 2.4, 2.5)
ERROR: No matching distribution found for hydra==1.0.4

and then next at the File Upload part it just hangs waiting for me to upload a file:
from google.colab import files
files.upload()

**Comment by ogunlao** [comment]
The notebooks were made with another branch of the saint repo called "saint-orig".  A fix is made
