### ISSUE TITLE
Colab Notebook Error

### ISSUE THREAD

**Issue by impulsecorp** [ogunlao/saint#2]
When I run your Colab Notebook at https://github.com/ogunlao/saint/blob/main/notebooks/Bank_Dataset.ipynb I get this error:

# separate 200 samples for supervised training, all others are used in ssl training
num_supervised_train_data = 200 

# get split indices
sup_train_indices, val_indices, test_indices, ssl_train_indices = generate_splits(len(bank_df), 
                                                                            num_supervised_train_data,
                                                                            args['preproc']['validation_split'],
                                                                            args['preproc']['test_split'],
                                                                            args['seed'],)

---------------------------------------------------------------------------

UnboundLocalError                         Traceback (most recent call last)

<ipython-input-12-838c1629cad2> in <module>()
      7                                                                             args['preproc']['validation_split'],
      8                                                                             args['preproc']['test_split'],
----> 9                                                                             args['seed'],)

/content/saint/src/dataset.py in generate_splits(dataset_size, num_supervised_train_data, validation_split, test_split, random_seed, shuffle_dataset)
     80         ssl_train_indices = indices[split_test+split_val+num_supervised_train_data: ]
     81 
---> 82     return sup_train_indices, val_indices, test_indices, ssl_train_indices
     83 
     84 

UnboundLocalError: local variable 'test_indices' referenced before assignment

**Comment by ogunlao** [comment]
This was a bug in the generate_split function. Thank you for reporting it.

**Comment by impulsecorp** [comment]
That fixed it, although there is another small issue. When I run your fixed notebook in Colab, it works but doesn't run on a GPU by default, even though Colab is set to use a GPU.  It gives a mesage saying "GPU available but not used.", like this:

Global seed set to 1234
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:1567: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  "GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`."

  | Name                | Type            | Params
--------------------------------------------------------
0 | transformer         | Encoder         | 65.0 K
1 | embedding           | Embedding       | 1.9 K 
2 | contrastive_loss_fn | ContrastiveLoss | 139 K 
3 | denoising_loss_fn   | DenoisingLoss   | 1.7 K 
--------------------------------------------------------
208 K     Trainable params
0         Non-trainable params
208 K     Total params
0.832     Total estimated model params size (MB)
Global seed set to 1234
Epoch 0:   0% 0/1125 [00:00<?, ?it/s] [W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch 0:  43% 480/1125 [01:23<01:51,  5.78it/s, loss=267, v_num=0, train_loss_step=247.0]

**Comment by ogunlao** [comment]
GPU is not used by default. To use GPU, you will have to set the number of gpus in the config.yaml file under trainer.gpu = 1 i.e. set gpu = 1
